window.FILE_EXTENSIONS = {
  "3dm": "Rhino 3D Model",
  "3ds": "3D Studio Scene",
  "3g2": "3GPP2 Multimedia File",
  "3gp": "3GPP Multimedia File",
  "7z": "7-Zip Compressed File",
  "aac": "Advanced Audio Coding File",
  "ac3": "Audio Codec 3 File",
  "ai": "Adobe Illustrator File",
  "aif": "Audio Interchange File Format",
  "amr": "Adaptive Multi-Rate Codec File",
  "apk": "Android Package File",
  "app": "macOS Application",
  "arw": "Sony Digital Camera Image",
  "asf": "Advanced Systems Format File",
  "asp": "Active Server Page",
  "aspx": "Active Server Page Extended File",
  "avi": "Audio Video Interleave File",
  "bak": "Backup File",
  "bat": "Batch File",
  "bin": "Binary File",
  "bmp": "Bitmap Image",
  "bz2": "Bzip2 Compressed File",
  "c": "C/C++ Source Code File",
  "cab": "Windows Cabinet File",
  "cad": "Computer-Aided Design File",
  "cdr": "CorelDRAW Image File",
  "cfg": "Configuration File",
  "cgm": "Computer Graphics Metafile",
  "chm": "Compiled HTML Help File",
  "class": "Java Class File",
  "cmd": "Windows Command File",
  "cpp": "C++ Source Code File",
  "cr2": "Canon Raw Image File",
  "css": "Cascading Style Sheet",
  "csv": "Comma-Separated Values File",
  "cue": "Cue Sheet File",
  "cur": "Windows Cursor",
  "dat": "Data File",
  "db": "Database File",
  "dbf": "Database File",
  "dds": "DirectDraw Surface",
  "dng": "Digital Negative Image File",
  "doc": "Microsoft Word Document",
  "docx": "Microsoft Word Open XML Document",
  "dwg": "AutoCAD Drawing Database File",
  "dxf": "Drawing Exchange Format File",
  "eml": "Email Message",
  "eps": "Encapsulated PostScript File",
  "exe": "Windows Executable File",
  "fla": "Adobe Animate Animation",
  "flac": "Free Lossless Audio Codec File",
  "flv": "Flash Video File",
  "fnt": "Windows Font File",
  "fon": "Generic Font File",
  "gif": "Graphical Interchange Format File",
  "gz": "Gnu Zipped Archive",
  "h": "C/C++ Header File",
  "htm": "Hypertext Markup Language File",
  "html": "Hypertext Markup Language File",
  "ics": "Calendar File",
  "iff": "Interchange File Format",
  "indd": "Adobe InDesign Document",
  "iso": "Disc Image File",
  "jar": "Java Archive File",
  "java": "Java Source Code File",
  "jpeg": "JPEG Image File",
  "jpg": "JPEG Image File",
  "js": "JavaScript File",
  "json": "JavaScript Object Notation File",
  "jsp": "Java Server Page",
  "key": "Keynote Presentation",
  "kml": "Keyhole Markup Language File",
  "kmz": "Google Earth Placemark File",
  "log": "Log File",
  "m3u": "Media Playlist File",
  "m4a": "MPEG-4 Audio File",
  "m4v": "iTunes Video File",
  "max": "3ds Max Scene File",
  "mdb": "Microsoft Access Database",
  "mdf": "Microsoft SQL Server Database File",
  "mid": "MIDI File",
  "mkv": "Matroska Video File",
  "mov": "Apple QuickTime Movie",
  "mp3": "MP3 Audio File",
  "mp4": "MPEG-4 Video File",
  "mpeg": "MPEG Movie",
  "mpg": "MPEG Video File",
  "msi": "Windows Installer Package",
  "nb": "Mathematica Notebook File",
  "numbers": "Numbers Spreadsheet",
  "obj": "Wavefront 3D Object File",
  "odp": "OpenDocument Presentation",
  "ods": "OpenDocument Spreadsheet",
  "odt": "OpenDocument Text Document",
  "ogg": "Ogg Vorbis Audio File",
  "otf": "OpenType Font",
  "pages": "Pages Document",
  "pct": "Picture File",
  "pdb": "Program Database",
  "pdf": "Portable Document Format",
  "pef": "Pentax Raw Image File",
  "php": "PHP Source Code File",
  "pkg": "macOS Installer Package",
  "pl": "Perl Script",
  "png": "Portable Network Graphic",
  "pps": "PowerPoint Slide Show",
  "ppt": "PowerPoint Presentation",
  "pptx": "PowerPoint Open XML Presentation",
  "prproj": "Premiere Pro Project File",
  "ps": "PostScript File",
  "psd": "Adobe Photoshop Document",
  "pst": "Outlook Personal Information Store File",
  "pub": "Publisher Document",
  "py": "Python Script",
  "rar": "WinRAR Compressed Archive",
  "raw": "Camera Raw Image File",
  "rm": "RealMedia File",
  "rtf": "Rich Text Format",
  "rw2": "Panasonic Raw Image File",
  "sh": "Bash Shell Script",
  "shtml": "Server Side Include HTML File",
  "sitx": "StuffIt X Archive",
  "sketch": "Sketch Drawing File",
  "slk": "Symbolic Link File",
  "sln": "Visual Studio Solution File",
  "sql": "Structured Query Language Data File",
  "srt": "SubRip Subtitle File",
  "svg": "Scalable Vector Graphics File",
  "swf": "Shockwave Flash Movie",
  "tar": "Consolidated Unix File Archive",
  "tex": "LaTeX Source Document",
  "tif": "Tagged Image File",
  "tiff": "Tagged Image File Format",
  "torrent": "BitTorrent File",
  "ttf": "TrueType Font",
  "txt": "Plain Text File",
  "vcf": "vCard File",
  "vob": "DVD Video Object File",
  "wav": "WAVE Audio File",
  "webm": "WebM Video File",
  "wma": "Windows Media Audio File",
  "wmv": "Windows Media Video File",
  "wpd": "WordPerfect Document",
  "wps": "Microsoft Works Word Processor Document",
  "xlr": "Works Spreadsheet",
  "xls": "Microsoft Excel Spreadsheet",
  "xlsx": "Excel Open XML Spreadsheet",
  "xml": "Extensible Markup",
  "": "Binary"
}